package com.bladesinthedark.crew;

import com.bladesinthedark.rules.Dice;

public enum NamedFaction {
	BARROWCLEFT, BILLHOOKS, BLUECOATS, BRIGADE, BRIGHTSTONE, CABBIES, CHARHOLLOW, CHARTERHALL, CHURCH_OF_ECSTASY, CIRCLE_OF_FLAME, CITY_COUNCIL, COALRIDGE, CROWS, CROWS_FOOT, CYPHERS, DAGGER_ISLES_CONSULATE, DEATHLANDS_SCAVENGERS, DIMMER_SISTERS, DOCKERS, DOCKS, DUNSLOUGH, FOG_HOUNDS, FORGOTTEN_GODS, FOUNDATION, GONDOLIERS, GRAY_CLOAKS, GRINDERS, HIVE, HORDE, IMPERIAL_MILITARY, INK_RAKES, INSPECTORS, IRONHOOK_PRISON, IRUVIAN_CONSULATE, LABORERS, LAMPBLACKS, LEVIATHAN_HUNTERS, LORD_SCURLOCK, LOST, MINISTRY_OF_PRESERVATION, NIGHTMARKET, PATH_OF_ECHOES, RAIL_JACKS, RECONCILED, RED_SASHES, SAILORS, SERVANTS, SEVEROSI_CONSULATE, SILKSHORE, SILVER_NAILS, SIX_TOWERS, SKOVLAN_CONSULATE, SKOVLANDER_REFUGEES, SPARKWRIGHTS, SPIRIT_WARDENS, ULF_IRONBORN, UNSEEN, WEEPING_LADY, WHITECROWN, WRAITHS, VULTURES;

	public static final NamedFaction[] ALL_FACTIONS = { BARROWCLEFT, BILLHOOKS,
	BLUECOATS, BRIGADE, BRIGHTSTONE, CABBIES,
	CHARHOLLOW, CHARTERHALL, CHURCH_OF_ECSTASY,
	CIRCLE_OF_FLAME, CITY_COUNCIL, COALRIDGE, CROWS,
	CROWS_FOOT, CYPHERS, DAGGER_ISLES_CONSULATE,
	DEATHLANDS_SCAVENGERS, DIMMER_SISTERS, DOCKERS, DOCKS,
	DUNSLOUGH, FOG_HOUNDS, FORGOTTEN_GODS, FOUNDATION,
	GONDOLIERS, GRAY_CLOAKS, GRINDERS, HIVE,
	HORDE, IMPERIAL_MILITARY, INK_RAKES, INSPECTORS,
	IRONHOOK_PRISON, IRUVIAN_CONSULATE, LABORERS,
	LAMPBLACKS, LEVIATHAN_HUNTERS, LORD_SCURLOCK, LOST,
	MINISTRY_OF_PRESERVATION, NIGHTMARKET, PATH_OF_ECHOES,
	RAIL_JACKS, RECONCILED, RED_SASHES, SAILORS,
	SERVANTS, SEVEROSI_CONSULATE, SILKSHORE, SILVER_NAILS,
	SIX_TOWERS, SKOVLAN_CONSULATE, SKOVLANDER_REFUGEES,
	SPARKWRIGHTS, SPIRIT_WARDENS, ULF_IRONBORN, UNSEEN,
	WEEPING_LADY, WHITECROWN, WRAITHS, VULTURES };
	public static final NamedFaction[] CITIZENRY = { BARROWCLEFT, BRIGHTSTONE,
	CHARHOLLOW, CHARTERHALL, COALRIDGE, CROWS_FOOT,
	DOCKS, DUNSLOUGH, NIGHTMARKET, SILKSHORE,
	SIX_TOWERS, WHITECROWN };
	public static final NamedFaction[] INSTITUTIONS = { BLUECOATS, BRIGADE,
	CITY_COUNCIL, DAGGER_ISLES_CONSULATE, IMPERIAL_MILITARY,
	INSPECTORS, IRONHOOK_PRISON, IRUVIAN_CONSULATE,
	LEVIATHAN_HUNTERS, MINISTRY_OF_PRESERVATION, SEVEROSI_CONSULATE,
	SKOVLAN_CONSULATE, SPARKWRIGHTS, SPIRIT_WARDENS };
	public static final NamedFaction[] LABOR_TRADE = { CABBIES, CYPHERS, DOCKERS,
	FOUNDATION, GONDOLIERS, INK_RAKES, LABORERS,
	RAIL_JACKS, SAILORS, SERVANTS };
	public static final NamedFaction[] THE_FRINGE = { CHURCH_OF_ECSTASY,
	DEATHLANDS_SCAVENGERS, FORGOTTEN_GODS, HORDE,
	PATH_OF_ECHOES, RECONCILED, SKOVLANDER_REFUGEES,
	WEEPING_LADY };
	public static final NamedFaction[] UNDERWORLD = { BILLHOOKS, CIRCLE_OF_FLAME,
	CROWS, DIMMER_SISTERS, FOG_HOUNDS, GRAY_CLOAKS,
	GRINDERS, HIVE, LAMPBLACKS, LORD_SCURLOCK,
	LOST, RED_SASHES, SILVER_NAILS, ULF_IRONBORN,
	UNSEEN, WRAITHS, VULTURES };
	public static NamedFaction randomFactionEnum() {
		return Dice.randomFromArray(ALL_FACTIONS);
	}
	public static NamedFaction randomCitizenryEnum() {
		return Dice.randomFromArray(CITIZENRY);
	}
	public static NamedFaction randomInstitutionEnum() {
		return Dice.randomFromArray(INSTITUTIONS);
	}
	public static NamedFaction randomLaborTradeEnum() {
		return Dice.randomFromArray(LABOR_TRADE);
	}
	public static NamedFaction randomFringeEnum() {
		return Dice.randomFromArray(THE_FRINGE);
	}
	public static NamedFaction randomUnderworldEnum() {
		return Dice.randomFromArray(UNDERWORLD);
	}
	public static NamedFaction[] factionAddOrder() {
		NamedFaction[] addOrder = new NamedFaction[] { IMPERIAL_MILITARY, CITY_COUNCIL,
				LEVIATHAN_HUNTERS, MINISTRY_OF_PRESERVATION, WHITECROWN,
				BRIGHTSTONE, CHARTERHALL, CHURCH_OF_ECSTASY,
				FOUNDATION, HIVE, IRONHOOK_PRISON, SPARKWRIGHTS,
				SPIRIT_WARDENS, UNSEEN, BLUECOATS, CIRCLE_OF_FLAME,
				DOCKERS, FORGOTTEN_GODS, GONDOLIERS, HORDE,
				INSPECTORS, IRUVIAN_CONSULATE, LABORERS,
				LORD_SCURLOCK, PATH_OF_ECHOES, RECONCILED, SAILORS,
				SILVER_NAILS, SIX_TOWERS, SKOVLAN_CONSULATE,
				SKOVLANDER_REFUGEES, BARROWCLEFT, BILLHOOKS,
				BRIGADE, CABBIES, COALRIDGE, CROWS,
				CROWS_FOOT, CYPHERS, DEATHLANDS_SCAVENGERS,
				DIMMER_SISTERS, DOCKS, GRAY_CLOAKS, GRINDERS,
				INK_RAKES, LAMPBLACKS, NIGHTMARKET, RAIL_JACKS,
				RED_SASHES, SERVANTS, SILKSHORE, WEEPING_LADY,
				WRAITHS, CHARHOLLOW, DAGGER_ISLES_CONSULATE,
				DUNSLOUGH, FOG_HOUNDS, LOST, SEVEROSI_CONSULATE,
				ULF_IRONBORN, VULTURES };
	
		return addOrder;
	}
}