package com.bladesinthedark.milieu;

public enum District {
	BARROWCLEFT, BRIGHTSTONE, CHARHOLLOW, CHARTERHALL, COALRIDGE, CROWS_FOOT, THE_DOCKS, DUNSLOUGH, NIGHTMARKET, SILKSHORE, SIX_TOWERS, WHITECROWN;

	//
	public static final District[] ALL_DISTRICTS = { BARROWCLEFT, BRIGHTSTONE, CHARHOLLOW,
			CHARTERHALL, COALRIDGE, CROWS_FOOT, THE_DOCKS, DUNSLOUGH,
			NIGHTMARKET, SILKSHORE, SIX_TOWERS, WHITECROWN };
}